### ISSUE TITLE
プラグインがうまく動かない件について

### ISSUE THREAD

**Issue by kobayashi47336** [kmuto/mackerel-plugin-pinglatency#5]
お世話になっております。
富士フイルムシステムサービス株式会社の小林です。

プラグインを作成いただきありがとうございます。

プラグインの設定するために
以下のコマンドを実行しましたが
mackerel-agent.confというファイルが開かれるのみで
特にカスタムメトリックが管理画面上で確認できるようにはなりませんでした。
mackerel-agent.conf [plugin.metrics.pinglatency] command = ["plugins\\bin\\mackerel-plugin-pinglatency.exe", "★★★"]

Windowsの「サービス」でmackerel-agentを再起動しても
特に表示が変わるということはありませんでした。

以下のコマンドがうまく実行できていないのでしょうか。
お手数おかけいたしますが、ご教授いただけますと幸いです。
mackerel-agent.conf [plugin.metrics.pinglatency] command = ["plugins\\bin\\mackerel-plugin-pinglatency.exe", "★★★"]

**Comment by kmuto** [comment]
@kobayashi47336 さんこんばんは。
このissueは全世界で見えてしまうので、ホストのところはマスキングさせていただきました。

README説明はある程度mackerel-agentに慣れている人を前提にしていたので、混乱を招いたかもしれません。

Windowsの場合は C:\Program Files\Mackerel\mackerel-agent の中に、mackerel-agent.conf というファイルがあるはずです。
これを管理者権限で編集します。
スタートの検索にnotepadと入れるとメモ帳が候補に出ると思うので、それを右クリックして「管理者として実行」。
開いたメモ帳で「開く」を選び、右下の「テキストファイル(*.txt)」を「すべてのファイル」に変更。これでC:\Program Files\Mackerel\mackerel-agentに進むと、mackerel-agent.confが見えるはずなので、それを開く。

あとはファイルの末尾に
```
[plugin.metrics.pinglatency]
command = ["plugins\\bin\\mackerel-plugin-pinglatency.exe", "接続先ホスト"]
```
を書いて保存し、サービスで再起動するのですが、

- 「接続先ホスト」には通信テストの相手方となるホストを指定します。自分のホストからその通信先ホストに通信テストをして、返ってくる時間で通信状況を調べる、という仕掛けです。
- そして「接続先ホスト」にはWindowsやMackerelで見える名前ではなく、DNSで決められた名前(たとえばwww.google.com)またはIPアドレス(たとえば192.168.1.1)となります。ご質問の★★★でマスクしたところを鑑みるに、もしmackerel-agent.confの編集はちゃんとできていたということであれば、これがうまくいかなかった理由です。

なお、通信テストにはICMP pingという仕組みを使っていますが、これは特定のサーバーやルーターを想定しているものなので、もしテストしたい接続先がインターネット上の他社の何かのアプリケーションサービスという場合はうまくいかない可能性があります(この場合、アプリケーションサービス側から何らかの品質テストツールが提供されていないと、どうしても難しいでしょう)。

**Comment by kobayashi47336** [comment]
ご連絡ありがとうございます。
詳しく説明していただき助かりました。
試してみて、またわからなかった際は質問させてください。
よろしくお願いいたします。

**Comment by kobayashi47336** [comment]
先日はプラグインに関しまして
詳しく教えていただきましてありがとうございました。

導入を検討していたのですが
1秒単位での監視をしたいという点で
弊社の要望とあわないというお話になりまして
導入を見送らせていただく運びになりました。

プラグインをご作成いただいたにも関わらず申し訳ございません。
またご縁がございましたらよろしくお願いいたします。

**Comment by kmuto** [comment]
@kobayashi47336 さん、ご丁寧にありがとうございます!
プラグイン自体は世の中に利用を求めている方もいるとは思いますし、私の技術素振りとしても良い経験でしたので、お気になさらないでください。

Mackerelで秒単位となるとメトリックではなくトレースを利用すれば記録自体はできそうですが、そもそも2点間で秒レベルの通信状態を見るためには計測の実装や、計測自体によるオーバーヘッドや負荷などけっこう難しいことを考慮する必要があるのではないかと思いました。
ほかにMackerelが当てはめられるかもしれない監視・オブザーバビリティの対象がございましたら、Mackerel窓口までご相談くださいませ!
